### ISSUE TITLE
IndexError: list index out of range after running a search on an already-created index.

### ISSUE THREAD

**Issue by tm17-abcgen** [bclavie/RAGatouille#3]
I ran through the first example notebook:
https://github.com/bclavie/RAGatouille/blob/main/examples/01-basic_indexing_and_search.ipynb

After the last indexing i resetted the Kernel and the notebook. Then i tried the following lines:

```python
from ragatouille import RAGPretrainedModel

path_to_index = ".ragatouille/colbert/indexes/Miyazaki/"
RAG = RAGPretrainedModel.from_index(path_to_index)
k=3
all_results = RAG.search(query=["What is the highest grossing movie from Studio Ghibli?", "What is the name of the most recent Studio Ghibli movie?"], k=k)
all_results
```

And it gave me the following:

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[3], [line 6](vscode-notebook-cell:?execution_count=3&line=6)
      [4](vscode-notebook-cell:?execution_count=3&line=4) RAG = RAGPretrainedModel.from_index(path_to_index)
      [5](vscode-notebook-cell:?execution_count=3&line=5) k=3
----> [6](vscode-notebook-cell:?execution_count=3&line=6) all_results = RAG.search(query=["What is the highest grossing movie from Studio Ghibli?", "What is the name of the most recent Studio Ghibli movie?"], k=k)
      [7](vscode-notebook-cell:?execution_count=3&line=7) all_results

File [~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:179](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:179), in RAGPretrainedModel.search(self, query, index_name, k, force_fast, zero_index_ranks, **kwargs)
    [153](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:153) def search(
    [154](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:154)     self,
    [155](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:155)     query: Union[str, list[str]],
   (...)
    [160](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:160)     **kwargs,
    [161](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:161) ):
    [162](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:162)     """Query an index.
    [163](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:163) 
    [164](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:164)     Parameters:
   (...)
    [177](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:177)     ```
    [178](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:178)     """
--> [179](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:179)     return self.model.search(
    [180](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:180)         query=query,
    [181](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:181)         index_name=index_name,
    [182](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py:182)         k=k,
...
     [23](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/colbert/data/collection.py:23) def __getitem__(self, item):
     [24](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/colbert/data/collection.py:24)     # TODO: Load from disk the first time this is called. Unless self.data is already not None.
---> [25](https://file+.vscode-resource.vscode-cdn.net/home/tm16/Work/00_RandomCoding/RAGatouille/v001/~/Work/00_RandomCoding/RAGatouille/v001/venv/lib/python3.11/site-packages/colbert/data/collection.py:25)     return self.data[item]

IndexError: list index out of range
```

Thanks in advance :)

EDIT: If it is still a ToDo, then nevermind that.

**Comment by bclavie** [comment]
Hey, thank you for flagging! This was due to RAGatouille not exporting collection properly to disk, resulting in loading a far too short list when reloading the index! I've just pushed an updated version to PyPi where (experimentally) it should work properly, please let me know if you run into another issue!

**Comment by hochbergg** [comment]
I seem to still have this issue, on Mac with 0.0.4b1.
I indexed ~7k documents with the following code:

> from ragatouille import RAGPretrainedModel
> from ragatouille.data import CorpusProcessor
> from tqdm import tqdm
> 
> from dao import Storage
> 
> if __name__ == '__main__':
>     RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")
>     db = Storage('db')
>     processor = CorpusProcessor()
> 
>     documents = []
>     for item in tqdm(db.get_all_items()):
>         documents.append(json.loads(item[2])['text'])
> 
>     print(type(documents), type(documents[0])) # This outputs list, str
>     processed = processor.process_corpus(documents)
>     print(type(processed), type(processed[0])) # This outputs list, str
> 
>     index_name = RAG.index(index_name='rag_test', collection=processed)
> 
>     print('---')
>     print(index_name)

Then I try querying with:

> from ragatouille import RAGPretrainedModel
> 
> query = "What manga did Hayao Miyazaki write?"
> RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0")
> results = RAG.search(query, index_name="colbert/indexes/rag_test")
> 
> print(results)

And get 

>   File "/Users/gal/Library/Caches/pypoetry/virtualenvs/knowledgedb-OLhc9Epa-py3.9/lib/python3.9/site-packages/colbert/data/collection.py", line 25, in __getitem__
>     return self.data[item]
> IndexError: list index out of range

With self.data being:
> 0 = {str} 'list with 7077 elements starting with...'
> 1 = {list: 3} [...]

**Comment by bclavie** [comment]
@hochbergg Thanks for flagging, this is a good catch!

This is due to me having missed an important update on the README. The way to load an existing index is no longer `RAGPretrainedModel.from_pretrained()` but `RAGPretrainedModel.from_index(index_path)`.

I'm also hoping to restore support for the previous way, but am fiddling with the best way for the config to work for this. I'll update the README asap to clear up the confusion, let me know if it works for you!

**Comment by hochbergg** [comment]
Changed to 

```
query = "What are some examples of adversarial AI attacks?"
RAG = RAGPretrainedModel.from_index(".ragatouille/colbert/indexes/rag_test")
results = RAG.search(query)

print(results)
```

And it works. Thank you. (Haven't seen the README update yet, but extrapolated from other example code)
